name: Deploy to Raspberry Pi

on:
  push:
    branches: ["main"]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Copy SSH Key
        run: |
          echo "${{ secrets.PI_SSH_KEY }}" > hermes_key
          chmod 600 hermes_key

      - name: Deploy to Raspberry Pi
        run: |
          ssh -o StrictHostKeyChecking=no -i hermes_key ${{ secrets.PI_USER }}@${{ secrets.PI_HOST }} "
            cd ~/Documents/GitHub/hermes &&
            git pull &&
            mvn clean package &&
            docker compose down &&
            docker compose up -d --build
          "
